apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/plabonaws-lab/flux-demo
  ref:
    branch: main
  secretRef:
    name: flux-system  # or whatever SSH secret you use to access the repo

