apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
        - name: admin-panel
        # {"$imagepolicy": "flux-system:admin-panel"}
          image: plabondocker/adminorderonline  # Use your current image tag here
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: admin-secret

