# clusters/my-cluster/app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - image-repository.yaml
  - image-policy.yaml
namespace: default

images:
  - name: plabondocker/adminorderonline
    newTag: v4

