apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  namespace: default
spec:
  selector:
    app: admin-panel
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

