apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  annotations:
    reconcile.fluxcd.io/requestedAt: "2025-05-19T16:45:26.489994204+06:00"
spec:
  interval: 1m0s
  url: ssh://git@github.com/plabonaws-lab/flux-demo
  ref:
    branch: main
  secretRef:
    name: git-credentials-secret1
  timeout: 60s

