apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin-panel
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo   # ✅ Corrected this line
    namespace: flux-system
  targetNamespace: default

