apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: admin-panel
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: admin-panel
  policy:
    semver:
      range: ">=v1.0.0"

