apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: admin-panel
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: your.real.email@example.com
        name: fluxcdbot
      messageTemplate: 'Update admin-panel image tag to {{ .NewTag }}'
    push:
      branch: main
  update:
    path: clusters/my-cluster/app
    strategy: Setters

